FROM node:lts-alpine@sha256:19eaf41f3b8c2ac2f609ac8103f9246a6a6d46716cdbe49103fdb116e55ff0cc

USER root

# Update packages as a result of Anchore security vulnerability checks
RUN apk update && \
    apk add --upgrade gnutls binutils nodejs apk-tools libjpeg-turbo libcurl libx11 libxml2

# Setup nodejs group & nodejs user
RUN addgroup --system nodejs --gid 998 && \
    adduser --system nodejs --uid 999 --home /test/ && \
    chown -R 999:998 /test/

USER 999

WORKDIR /test

COPY --chown=999:998 . /test

RUN yarn install --frozen-lockfile && \
    yarn run postinstall

CMD npm run test:acceptance
